### ISSUE TITLE
ModuleNotFoundError: No module named 'lib'

### ISSUE THREAD

**Issue by hxiaoj** [RozDavid/UnScene3D#1]
Hello!
When I run '. scripts/unscene3d_dino_2d3d.sh', I get the following error:

Traceback (most recent call last):
  File "unscene3d_pseudo_main.py", line 15, in <module>
    from datasets import load_dataset
  File "/UnScene3D/pseudo_masks/datasets/__init__.py", line 1, in <module>
    from lib.datasets import scannet, scannet_solo, scannet_free, arkit, s3dis
ModuleNotFoundError: No module named 'lib'

Can you help me?

**Comment by RozDavid** [comment]
Hey @hxiaoj, 

Thanks a lot for flagging this, indeed I mad an error with relative paths when refactoring the code for release. 
Closing the issue as should be fixed now, but please feel free to reopen if you still have the same issue after pulling the repo again. 

Cheers, 
David

**Comment by hxiaoj** [comment]
Hello!
When I run '. scripts/unscene3d_dino_2d3d.sh', I get a new error:

hydra.errors.MissingConfigException: Could not load override hydra/launcher/submitit_slurm

Can you help me?

**Comment by RozDavid** [comment]
hey @hxiaoj, 

you are probably missing the hydra launcher plugin. Please refer [here](https://hydra.cc/docs/plugins/submitit_launcher/) for the install command.

**Comment by RozDavid** [comment]
#2 duplicate
