### ISSUE TITLE
. scripts/unscene3d_dino_2d3d.sh

### ISSUE THREAD

**Issue by zyjhxd** [RozDavid/UnScene3D#11]
在运行. scripts/unscene3d_dino_2d3d.sh代码时出现错误[2024-09-20 15:13:17,365][root][INFO] - ===> Initializing dataloader
Error executing job with overrides: ['misc.comment=cutler3d_CSC_DINO', 'freemask.affinity_tau=0.6', 'freemask.modality=both', 'data.segments_min_vert_nums=[50]', 'freemask.min_segment_size=4', 'test.visualize=true', '+save_dir=outputs/']
Traceback (most recent call last):
  File "unscene3d_pseudo_main.py", line 536, in main
    model, data_loader, dataset = initialize_models(config, device)
  File "unscene3d_pseudo_main.py", line 43, in initialize_models
    data_loader = initialize_data_loader(DatasetClass, config=config, phase=config.train.train_phase,
  File "/root/autodl-tmp/UnScene3D/pseudo_masks/datasets/dataset.py", line 534, in initialize_data_loader
    dataset = DatasetClass(
  File "/root/autodl-tmp/UnScene3D/pseudo_masks/datasets/scannet.py", line 60, in __init__
    self.data_paths = np.array(sorted(read_txt(os.path.join(data_root, f'{phase}.txt'))))
  File "/root/autodl-tmp/UnScene3D/pseudo_masks/../utils/utils.py", line 448, in read_txt
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/ScanNet/scannet_200_insseg/train.txt'
但我在这个路径下是有这个文件的，请问是什么原因呢？

**Comment by RozDavid** [comment]
duplicate issue to the closed #7, please check the updated readme.
