### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.transforms'

### ISSUE THREAD

**Issue by hualuojingye** [RozDavid/UnScene3D#4]
When I run “scripts/eval/eval_all_datasets.sh”, I got the error about：
Traceback (most recent call last):
  File "pseudo_masks/eval_freemask_gt_performance.py", line 7, in <module>
    from datasets import load_dataset
  File "/home/Unscene3D/pseudo_masks/datasets/__init__.py", line 1, in <module>
    from datasets import scannet, scannet_free, arkit, s3dis
  File "/home/Unscene3D/pseudo_masks/datasets/scannet.py", line 14, in <module>
    from datasets.dataset import VoxelizationDataset, DatasetPhase, str2datasetphase_type
  File "/home/Unscene3D/pseudo_masks/datasets/dataset.py", line 18, in <module>
    import utils.transforms as t
ModuleNotFoundError: No module named 'utils.transforms'
how can I solve this problem, thank you very much!

**Comment by RozDavid** [comment]
you'd have to add the root repo path to your python path. The module that the script is trying to import is available [here](https://github.com/RozDavid/UnScene3D/blob/main/utils/transforms.py).

**Comment by RozDavid** [comment]
did you managed to solve this? closing the issue for now as worked for others, but please feel free to reopen if still struggling.
